/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package dsys.gpsmartseafoodmonitor;

import generated.grpc.oceanmonitoring.Location;
import generated.grpc.oceanmonitoring.OceanData;
import generated.grpc.oceanmonitoring.OceanMonitoringServiceGrpc;
import io.grpc.ManagedChannel;
import io.grpc.ManagedChannelBuilder;
import javax.jmdns.ServiceInfo;

/**
 *
 * @author gport
 */
public class SeafoodGUI extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(SeafoodGUI.class.getName());

    /**
     * Creates new form SeafoodGUI
     */
    public SeafoodGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Input = new javax.swing.JPanel();
        Location = new javax.swing.JLabel();
        locationField = new javax.swing.JTextField();
        Species = new javax.swing.JLabel();
        speciesField = new javax.swing.JTextField();
        Buttons = new javax.swing.JPanel();
        oceanButton = new javax.swing.JButton();
        evaluateButton = new javax.swing.JButton();
        recommendationsButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        Output = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        outputarea = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        Location.setText("Location");

        locationField.setText("Dublin");
        locationField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                locationFieldActionPerformed(evt);
            }
        });

        Species.setText("Species");

        speciesField.setText("Tuna");
        speciesField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                speciesFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout InputLayout = new javax.swing.GroupLayout(Input);
        Input.setLayout(InputLayout);
        InputLayout.setHorizontalGroup(
            InputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InputLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(InputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Location)
                    .addComponent(Species))
                .addGap(101, 101, 101)
                .addGroup(InputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(locationField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(speciesField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        InputLayout.setVerticalGroup(
            InputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InputLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(InputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Location)
                    .addComponent(locationField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(InputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Species)
                    .addComponent(speciesField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(47, Short.MAX_VALUE))
        );

        oceanButton.setText("Check Ocean");
        oceanButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oceanButtonActionPerformed(evt);
            }
        });

        evaluateButton.setText("Evaluate Seafood");
        evaluateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                evaluateButtonActionPerformed(evt);
            }
        });

        recommendationsButton.setText("Get Recommendations");
        recommendationsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recommendationsButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("Services");

        javax.swing.GroupLayout ButtonsLayout = new javax.swing.GroupLayout(Buttons);
        Buttons.setLayout(ButtonsLayout);
        ButtonsLayout.setHorizontalGroup(
            ButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ButtonsLayout.createSequentialGroup()
                .addGap(255, 255, 255)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(ButtonsLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(oceanButton)
                .addGap(88, 88, 88)
                .addComponent(evaluateButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 93, Short.MAX_VALUE)
                .addComponent(recommendationsButton)
                .addContainerGap())
        );
        ButtonsLayout.setVerticalGroup(
            ButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ButtonsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(ButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(evaluateButton)
                    .addComponent(recommendationsButton)
                    .addComponent(oceanButton))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        outputarea.setColumns(20);
        outputarea.setRows(5);
        jScrollPane1.setViewportView(outputarea);

        javax.swing.GroupLayout OutputLayout = new javax.swing.GroupLayout(Output);
        Output.setLayout(OutputLayout);
        OutputLayout.setHorizontalGroup(
            OutputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        OutputLayout.setVerticalGroup(
            OutputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)
        );

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("Smart Seafood Monitor ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Input, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Buttons, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Output, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(176, 176, 176)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Buttons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Output, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void locationFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_locationFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_locationFieldActionPerformed

    private void oceanButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oceanButtonActionPerformed
        // TODO add your handling code here:
        String location = locationField.getText();
        

try {
    ServiceInfo serviceInfo = SmartSeafoodServiceDiscovery.discoverService("_oceanmonitoring._tcp.local.");

    if (serviceInfo == null) {
        outputarea.setText("Ocean service not found");
        return;
    }

    String host = serviceInfo.getHostAddresses()[0];
    int port = serviceInfo.getPort();

    ManagedChannel channel = ManagedChannelBuilder
            .forAddress(host, port)
            .usePlaintext()
            .build();

   generated.grpc.oceanmonitoring.OceanMonitoringServiceGrpc.OceanMonitoringServiceBlockingStub stub =
            generated.grpc.oceanmonitoring.OceanMonitoringServiceGrpc.newBlockingStub(channel);

    generated.grpc.oceanmonitoring.Location request = generated.grpc.oceanmonitoring.Location.newBuilder()
            .setLocation(location)
            .build();

    generated.grpc.oceanmonitoring.OceanData response = stub.currentOceanConditions(request);

    outputarea.setText(
            "Ocean Conditions for " + location + "\n\n" +
            "Temperature: " + response.getTemperatureC() + "\n" +
            "Oxygen: " + response.getOxygenLevel() + "\n" +
            "pH: " + response.getAcidityPH() + "\n" +
            "Pollution: " + response.getPollutionLevel()
    );

    channel.shutdown();

} catch (Exception e) {
    outputarea.setText("Error: " + e.getMessage());
}
    }//GEN-LAST:event_oceanButtonActionPerformed

    private void evaluateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_evaluateButtonActionPerformed
        // TODO add your handling code here:
        String location = locationField.getText();
        String species = speciesField.getText();


try {
    ServiceInfo serviceInfo = SmartSeafoodServiceDiscovery.discoverService("_seafoodmonitoring._tcp.local.");

    if (serviceInfo == null) {
        outputarea.setText("Seafood service not found");
        return;
    }

    String host = serviceInfo.getHostAddresses()[0];
    int port = serviceInfo.getPort();

    ManagedChannel channel = ManagedChannelBuilder
            .forAddress(host, port)
            .usePlaintext()
            .build();

    generated.grpc.seafoodmonitoring.SeafoodMonitoringServiceGrpc.SeafoodMonitoringServiceBlockingStub stub =
            generated.grpc.seafoodmonitoring.SeafoodMonitoringServiceGrpc.newBlockingStub(channel);

    generated.grpc.seafoodmonitoring.SeafoodRequest request =
            generated.grpc.seafoodmonitoring.SeafoodRequest.newBuilder()
                    .setSpecies(species)
                    .setLocation(location)
                    .build();

    generated.grpc.seafoodmonitoring.SeafoodEvaluation response = stub.evaluateSeafood(request);

    outputarea.setText(
            "Seafood Evaluation\n\n" +
            "Species: " + response.getSpecies() + "\n" +
            "Safe to eat: " + response.getSafeToEat() + "\n" +
            "Sustainable: " + response.getSustainable() + "\n" +
            "Alarm: " + response.getAlarm()
    );

    channel.shutdown();

} catch (Exception e) {
    outputarea.setText("Error:\n" + e.getMessage());
}
        
    }//GEN-LAST:event_evaluateButtonActionPerformed

    private void recommendationsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recommendationsButtonActionPerformed
        // TODO add your handling code here:
          String location = locationField.getText();
          String species = speciesField.getText();
          
   
    try {
        ServiceInfo serviceInfo = SmartSeafoodServiceDiscovery.discoverService("_recommendation._tcp.local.");

        if (serviceInfo == null) {
            outputarea.setText("Recommendation service not found");
            return;
        }

        String host = serviceInfo.getHostAddresses()[0];
        int port = serviceInfo.getPort();

        ManagedChannel channel = ManagedChannelBuilder
                .forAddress(host, port)
                .usePlaintext()
                .build();

        generated.grpc.recommendation.RecommendationServiceGrpc.RecommendationServiceStub stub =
                generated.grpc.recommendation.RecommendationServiceGrpc.newStub(channel);

        StringBuilder result = new StringBuilder();

        io.grpc.stub.StreamObserver<generated.grpc.recommendation.RecommendationResponse> responseObserver =
                new io.grpc.stub.StreamObserver<generated.grpc.recommendation.RecommendationResponse>() {
            @Override
            public void onNext(generated.grpc.recommendation.RecommendationResponse response) {
                result.append("Recommendations\n\n");
                result.append("Recommended: ").append(response.getRecommendedSpeciesList()).append("\n");
                result.append("Avoid: ").append(response.getAvoidSpeciesList()).append("\n");
            }

            @Override
            public void onError(Throwable t) {
                outputarea.setText("Error: " + t.getMessage());
            }

            @Override
            public void onCompleted() {
                outputarea.setText(result.toString());
            }
        };

        io.grpc.stub.StreamObserver<generated.grpc.recommendation.RecommendationRequest> requestObserver =
                stub.liveRecommendations(responseObserver);

        requestObserver.onNext(
                generated.grpc.recommendation.RecommendationRequest.newBuilder()
                        .setLocation(location)
                        .setSelectedSpecies(species)
                        .setReason("GUI request")
                        .build()
        );

        requestObserver.onCompleted();

    } catch (Exception e) {
        outputarea.setText("Error:\n" + e.getMessage());
    }
    }//GEN-LAST:event_recommendationsButtonActionPerformed

    private void speciesFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_speciesFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_speciesFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new SeafoodGUI().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Buttons;
    private javax.swing.JPanel Input;
    private javax.swing.JLabel Location;
    private javax.swing.JPanel Output;
    private javax.swing.JLabel Species;
    private javax.swing.JButton evaluateButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField locationField;
    private javax.swing.JButton oceanButton;
    private javax.swing.JTextArea outputarea;
    private javax.swing.JButton recommendationsButton;
    private javax.swing.JTextField speciesField;
    // End of variables declaration//GEN-END:variables
}
